robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5]

hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [gripper_finger1_joint]

joint_state_controller:
  type: "joint_state_controller/JointStateController" 
  publish_rate: 10   
