controller_list:
  - name: fake_arm_gp_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_gripper_gp_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: arm_gp
    pose: default_pose
  - group: gripper_gp
    pose: grab_pose